### ISSUE TITLE
Fix Ruby Fixnum override

### ISSUE THREAD

**Issue by cielavenir** [cielavenir/procon#8]
It was removed in 3.2 cf https://www.ruby-lang.org/en/news/2022/12/25/ruby-3-2-0-released/

**Comment by FIshInMoon** [comment]
你好，你的来信已收到，我会尽快回复，谢谢！（自动回复）

**Comment by cielavenir** [comment]
hopefully can be fixed just by putting `Fixnum=Integer if !defined?(Fixnum)`

**Comment by cielavenir** [comment]
Fixed by https://github.com/cielavenir/procon/commit/0aefe5d03b26096eacd1747c2da8f77a9b40fe5f
